# PRODUCTION DOCKERFILE
# ---------------------
# This Dockerfile allows to build a Docker image for an Angular application
# and based on a NodeJS 20 image. The multi-stage mechanism allows to build
# the application in a "builder" stage and then create a production
# image containing the required dependencies and the JS build files.

# For manual build you can execute:
# docker build . --target=deployment --name=insta-share-angular:1.0.0

#----------------------
#   Building stage
#----------------------

    FROM node:20 AS builder
    
    WORKDIR /home/node/app
    
    RUN npm install @angular/cli
    
    COPY package*.json ./
    
    RUN npm install
    
    COPY . .
    
    #----------------------
    #   Deployment stage
    #----------------------
    
    FROM node:20 AS deployment
    
    ENV NODE_ENV=dev
    
    WORKDIR /home/node/app
    
    COPY --from=builder /home/node/app .
    
    RUN ["npm", "run", "build"]
    
    #----------------------
    #   Production stage
    #----------------------
    
    FROM nginx as production
    
    COPY --from=deployment /home/node/app/dist/mulesoft-frontend-angular /var/www/html
    COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
    